name: Notion to Jekyll

on:
  # schedule is in UTC using cron syntax
  schedule:
    - cron: '0 20 * * *'

jobs:
  notion_to_jekyll:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Commit and push if changes
        env:
          PUBLISH_TO_POSTS: ${{ env.PUBLISH_TO_POSTS }}
        run: |
          mkdir -p test
          echo "test" > test/file.txt
        
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git add test
          git commit -S -m "New test"

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
