name: Notion to Jekyll

on:
  # schedule is in UTC using cron syntax
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  notion_to_jekyll:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Commit and push if changes
        env:
          PUBLISH_TO_POSTS: ${{ env.PUBLISH_TO_POSTS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESTINATION_BRANCH: main
        run: |
          mkdir -p test
          echo "test" > test/file.txt

          export TODAY=$( date -u '+%Y-%m-%d' )
          export FILE_TO_COMMIT="test/file.txt"
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content=@<( base64 -i $FILE_TO_COMMIT ) \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"
