name: Notion to Jekyll

on:
  # schedule is in UTC using cron syntax
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  notion_to_jekyll:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Commit and push if changes
        env:
          PUBLISH_TO_POSTS: ${{ env.PUBLISH_TO_POSTS }}
        run: |
          mkdir -p test
          echo "test" > test/file.txt

          curl -sSL 'https://github.com/pirafrank/fpiracom/raw/main/CNAME' --output CNAME
          DOMAIN=$(cat CNAME | head -n 1)
          EML="$(printf def | sed 's/f/v/' | sed "s/$/@${DOMAIN}/")"
          git config --local user.email "$EML"
          git config --local user.name 'Francesco Pira'

          git add test/file.txt
          git commit -S -m "New test"
          
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
